# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/Ragfood',
                'doc_host': 'https://frankausberlin.github.io',
                'git_url': 'https://github.com/frankausberlin/Ragfood',
                'lib_path': 'Ragfood'},
  'syms': {'Ragfood.core': {'Ragfood.core.foo': ('core.html#foo', 'Ragfood/core.py')}}}
