"""Main application class for Ragfood - Making knowledge from documents accessible for chats with LLMs"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/06_Ragfood.ipynb.

# %% auto 0
__all__ = ['Ragfood']

# %% ../nbs/06_Ragfood.ipynb 3
from ipywidgets import VBox, HTML, Accordion, Button, HBox, Box
from .mediator import Mediator
from .calibre import Calibre
from .booklist import Booklist
from .pdfview import PDFView

# %% ../nbs/06_Ragfood.ipynb 4
class Ragfood(Mediator):
    """Main application class for Ragfood.
    
    Making knowledge from documents accessible for chats with LLMs.
    Uses Calibre, ipywidgets, PyPDF2.
    """
    
    export_pdf_to_folder = '~/labor/ragfood_pdf'
    calibre_library_folder = '~/labor/test_calibre_with_4_pdfs'
    create_sample_library_with_4_books_if_library_folder_not_exists = True
    
    def __init__(self):
        """Initialize Ragfood application."""
        # the colleagues
        Calibre.create_sample_library_with_4_books_if_library_folder_not_exists = Ragfood.create_sample_library_with_4_books_if_library_folder_not_exists
        self.calibre = Calibre(mediator=self, title='Calibre',
                              library_folder=Ragfood.calibre_library_folder,
                              export_folder=Ragfood.export_pdf_to_folder)
        self.booklist = Booklist(books=self.calibre.book_list, mediator=self, heightListArea=620, behave='radio')
        self.pdfView = PDFView(mediator=self)
        
        # widgets
        title_html = f"""<div style="background-color: #f0f8ff; padding: 10px; "><h1 style="color: #005F6A; margin: 0;">🍲 Ragfood</h1></div>"""
        self.titleLine_hm = HTML(title_html)
        self.selectPDF_hb = HBox(children=[self.booklist.widget,
                                          VBox(children=[self.calibre.widget, self.pdfView.widget],
                                               layout={'width': '100%'})])
        self.processing_bx = Box()
        self.vectoreStore_bx = Box()
        self.chat_bx = Box()
        self.main_ac = Accordion(children=[self.selectPDF_hb, self.processing_bx, self.vectoreStore_bx, self.chat_bx])
        self.main_ac.set_title(0, '📚 Select PDF - from Calibre')
        self.main_ac.set_title(1, '⚗️ Processing PDF - Loader, Chunking, Embedding')
        self.main_ac.set_title(2, '🕋 Vectore Store - Chunks')
        self.main_ac.set_title(3, '🔎 Chat - using LLM to access knowledge')
        self.widget = VBox(children=[self.titleLine_hm, self.main_ac])
    
    def notify(self, colleague, event, state, *argc, **argv):
        """Handle notifications from colleagues."""
        if event == 'OnBooklistBookSelected':
            file = self.calibre.getPathByID(argv['calibre_id'])
            self.calibre.export([argv['calibre_id']])
            print('setPDF', file)
            self.pdfView.setPDF(file)
        # print(event, state, argc, argv)
