"""Global state constants for Ragfood"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/02_States.ipynb.

# %% auto 0
__all__ = ['RAGFOOD_OK', 'RAGFOOD_ERROR_CALIBRENOTFOUND', 'RAGFOOD_ERROR_LIBNOTFOUND', 'RAGFOOD_ERROR_CALIBRE_ID_UNKNOWN',
           'RAGFOOD_OPF_NOT_AVAILABLE', 'RAGFOOD_PDF_NOT_AVAILABLE', 'RAGFOOD_PDF_ERROR_READING_METADATA']

# %% ../nbs/02_States.ipynb 3
# State constants for Ragfood operations
# These constants define the various return codes and states that can occur
# during Ragfood operations, particularly when interfacing with Calibre
# and handling PDF files.

# Success state
RAGFOOD_OK = 0  # Operation completed successfully

# Calibre-related error states
RAGFOOD_ERROR_CALIBRENOTFOUND = 1      # Calibre software not found on system
RAGFOOD_ERROR_LIBNOTFOUND = 2          # Calibre library not found or inaccessible
RAGFOOD_ERROR_CALIBRE_ID_UNKNOWN = 4   # Invalid or unknown Calibre book ID

# Metadata and file format error states
RAGFOOD_OPF_NOT_AVAILABLE = 3          # OPF metadata file not available
RAGFOOD_PDF_NOT_AVAILABLE = 6          # PDF file not available for the book
RAGFOOD_PDF_ERROR_READING_METADATA = 7 # Error occurred while reading PDF metadata
